replicaCount: 2

image:  
#  repository: ghcr.io/nathansegers/fastapi-intro # You can keep this on my image, because of the Pull Secrets
  repository: ghcr.io/w-vanhoey/fastapi-intro   # package
  tag: v2.6.0

# nameOverride: "nathan-fastapi"
# fullNameOverride: "nathan-fastapi-demo"
nameOverride: "hoey-fastapi"
fullNameOverride: "hoey-fastapi-demo"

serviceAccount:
    create: true
    name: helm-service-account ## This is a name you can choose yourself

## Keep these empty for the first try.
##------------------------------------
#imagePullSecrets: [] # Here you can fill in your own Pull Secret  (empty = only for public repositories)
#nodeSelector: {} # Fill in the right Node Selector here.

## Second try.
##------------------------------------
nodeSelector:
    kubernetes.io/hostname: "vanhoey-wim"    # or    nodeName: "vanhoey-wim"
    kubernetes.io/os: "linux"
    #disktype: ssd

imagePullSecrets:
      - name: "ghcr-vanhoey-wim-3"           # Name of the secret

# imagePullSecrets: {{- toYaml . | nindent 8 }} # ERRORS
# imagePullSecrets: 
#    - name: {{ .Values.image.pullSecret }}
# imagePullSecrets:
#     - name: regcred
# nodeSelector: {"beta.kubernetes.io/arch": "amd64"}