replicaCount: 2

image:  
#  repository: ghcr.io/nathansegers/fastapi-intro # You can keep this on my image, because of the Pull Secrets
  repository: ghcr.io/w-vanhoey/fastapi-intro
  tag: v1.0.0

# nameOverride: "nathan-fastapi"
# fullNameOverride: "nathan-fastapi-demo"
nameOverride: "hoey-fastapi"
fullNameOverride: "hoey-fastapi-demo"

serviceAccount:
    create: true
    name: helm-service-account ## This is a name you can choose yourself

## Keep these empty for the first try.
imagePullSecrets: [] # Here you can fill in your own Pull Secret if you do want to work with your own repository
# nodeSelector: {} # Fill in the right Node Selector here.

#imagePullSecrets: {{- toYaml . | nindent 8 }} # ERRORS
# imagePullSecrets: 
#    - name: {{ .Values.image.pullSecret }}
# imagePullSecrets:
#     - name: regcred
nodeSelector: {"beta.kubernetes.io/arch": "amd64"}